<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE national_family_health_survey [
<!ELEMENT national_family_health_survey (national_family)>

<!ELEMENT national_family (District_Names,State_UT,Number_of_Households_surveyed,Number_of_Women_age_15-49_years_interviewed,Number_of_Men_age_15-54_years_interviewed,Female_population_age_6_years_and_above_who_ever_attended_school,Population_below_age_15_years,Sex_ratio_of_the_total_population_females_per_1000_males, Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males, Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority)>

<!ELEMENT national_family (#PCDATA)>
<!ELEMENT District_Names (#PCDATA)>
<!ELEMENT State_UT (#PCDATA)>
<!ELEMENT Number_of_Households_surveyed (#PCDATA)>
<!ELEMENT Number_of_Women_age_15-49_years_interviewed (#PCDATA)>
<!ELEMENT Number_of_Men_age_15-54_years_interviewed (#PCDATA)>
<!ELEMENT Female_population_age_6_years_and_above_who_ever_attended_school (#PCDATA)>
<!ELEMENT Population_below_age_15_years (#PCDATA)>
<!ELEMENT Sex_ratio_of_the_total_population_females_per_1000_males (#PCDATA)>
<!ELEMENT Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males (#PCDATA)>
<!ELEMENT Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority (#PCDATA)>

<!ATTLIST national_family row CDATA #REQUIRED>


]>

<national_family_health_survey>
	<national_family row ="1">
		<District_Names>Nicobars</District_Names>
		<State_UT>Andaman and Nicobar Islands</State_UT>
		<Number_of_Households_surveyed>882</Number_of_Households_surveyed>
		<Number_of_Women_age_15-49_years_interviewed>764</Number_of_Women_age_15-49_years_interviewed>
		<Number_of_Men_age_15-54_years_interviewed>125</Number_of_Men_age_15-54_years_interviewed>
		<Female_population_age_6_years_and_above_who_ever_attended_school>78</Female_population_age_6_years_and_above_who_ever_attended_school>
		<Population_below_age_15_years>23</Population_below_age_15_years>
		<Sex_ratio_of_the_total_population_females_per_1000_males>973</Sex_ratio_of_the_total_population_females_per_1000_males>
		<Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males>927</Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males>
		<Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority>98</Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority>
	</national_family>
	<national_family row ="2">
		<District_Names> North and Middle Andaman</District_Names>
		<State_UT>Andaman and Nicobar Islands</State_UT>
		<Number_of_Households_surveyed>874</Number_of_Households_surveyed>
		<Number_of_Women_age_15-49_years_interviewed>789</Number_of_Women_age_15-49_years_interviewed>
		<Number_of_Men_age_15-54_years_interviewed>108</Number_of_Men_age_15-54_years_interviewed>
		<Female_population_age_6_years_and_above_who_ever_attended_school>82.7</Female_population_age_6_years_and_above_who_ever_attended_school>
		<Population_below_age_15_years>19.8</Population_below_age_15_years>
		<Sex_ratio_of_the_total_population_females_per_1000_males>950</Sex_ratio_of_the_total_population_females_per_1000_males>
		<Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males>844</Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males>
		<Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority>100</Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority>
	</national_family>
	<national_family row ="3">
		<District_Names>South Andaman </District_Names>
		<State_UT>Andaman and Nicobar Islands</State_UT>
		<Number_of_Households_surveyed>868</Number_of_Households_surveyed>
		<Number_of_Women_age_15-49_years_interviewed>844</Number_of_Women_age_15-49_years_interviewed>
		<Number_of_Men_age_15-54_years_interviewed>134</Number_of_Men_age_15-54_years_interviewed>
		<Female_population_age_6_years_and_above_who_ever_attended_school>84.7</Female_population_age_6_years_and_above_who_ever_attended_school>
		<Population_below_age_15_years>21</Population_below_age_15_years>
		<Sex_ratio_of_the_total_population_females_per_1000_males>967</Sex_ratio_of_the_total_population_females_per_1000_males>
		<Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males>935</Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males>
		<Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority>96.5</Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority>
	</national_family>
	
	<national_family row ="4">
		<District_Names>Srikakulam </District_Names>
		<State_UT>Andhra Pradesh</State_UT>
		<Number_of_Households_surveyed>874</Number_of_Households_surveyed>
		<Number_of_Women_age_15-49_years_interviewed>780</Number_of_Women_age_15-49_years_interviewed>
		<Number_of_Men_age_15-54_years_interviewed>100</Number_of_Men_age_15-54_years_interviewed>
		<Female_population_age_6_years_and_above_who_ever_attended_school>60</Female_population_age_6_years_and_above_who_ever_attended_school>
		<Population_below_age_15_years>20.7</Population_below_age_15_years>
		<Sex_ratio_of_the_total_population_females_per_1000_males>1140</Sex_ratio_of_the_total_population_females_per_1000_males>
		<Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males>1163</Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males>
		<Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority>95</Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority>
	</national_family>


	<national_family row ="5">
		<District_Names>Vizianagaram </District_Names>
		<State_UT>Andhra Pradesh</State_UT>
		<Number_of_Households_surveyed>902</Number_of_Households_surveyed>
		<Number_of_Women_age_15-49_years_interviewed>853</Number_of_Women_age_15-49_years_interviewed>
		<Number_of_Men_age_15-54_years_interviewed>134</Number_of_Men_age_15-54_years_interviewed>
		<Female_population_age_6_years_and_above_who_ever_attended_school>56</Female_population_age_6_years_and_above_who_ever_attended_school>
		<Population_below_age_15_years>20.6</Population_below_age_15_years>
		<Sex_ratio_of_the_total_population_females_per_1000_males>1114</Sex_ratio_of_the_total_population_females_per_1000_males>
		<Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males>898</Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males>
		<Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority>95.4</Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority>
	</national_family>

	<national_family row ="6">
		<District_Names>Visakhapatnam </District_Names>
		<State_UT>Andhra Pradesh</State_UT>
		<Number_of_Households_surveyed>869</Number_of_Households_surveyed>
		<Number_of_Women_age_15-49_years_interviewed>818</Number_of_Women_age_15-49_years_interviewed>
		<Number_of_Men_age_15-54_years_interviewed>112</Number_of_Men_age_15-54_years_interviewed>
		<Female_population_age_6_years_and_above_who_ever_attended_school>66.8</Female_population_age_6_years_and_above_who_ever_attended_school>
		<Population_below_age_15_years>21.4</Population_below_age_15_years>
		<Sex_ratio_of_the_total_population_females_per_1000_males>1066</Sex_ratio_of_the_total_population_females_per_1000_males>
		<Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males>974</Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males>
		<Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority>90.5</Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority>
	</national_family>

	<national_family row ="7">
		<District_Names>East Godavari </District_Names>
		<State_UT>Andhra Pradesh</State_UT>
		<Number_of_Households_surveyed>888</Number_of_Households_surveyed>
		<Number_of_Women_age_15-49_years_interviewed>824</Number_of_Women_age_15-49_years_interviewed>
		<Number_of_Men_age_15-54_years_interviewed>105</Number_of_Men_age_15-54_years_interviewed>
		<Female_population_age_6_years_and_above_who_ever_attended_school>75.4</Female_population_age_6_years_and_above_who_ever_attended_school>
		<Population_below_age_15_years>20.5</Population_below_age_15_years>
		<Sex_ratio_of_the_total_population_females_per_1000_males>995</Sex_ratio_of_the_total_population_females_per_1000_males>
		<Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males>882</Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males>
		<Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority>93</Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority>
	</national_family>


	<national_family row ="8">
		<District_Names>West Godavari </District_Names>
		<State_UT>Andhra Pradesh</State_UT>
		<Number_of_Households_surveyed>884</Number_of_Households_surveyed>
		<Number_of_Women_age_15-49_years_interviewed>841</Number_of_Women_age_15-49_years_interviewed>
		<Number_of_Men_age_15-54_years_interviewed>122</Number_of_Men_age_15-54_years_interviewed>
		<Female_population_age_6_years_and_above_who_ever_attended_school>75.4</Female_population_age_6_years_and_above_who_ever_attended_school>
		<Population_below_age_15_years>21.5</Population_below_age_15_years>
		<Sex_ratio_of_the_total_population_females_per_1000_males>999</Sex_ratio_of_the_total_population_females_per_1000_males>
		<Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males>833</Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males>
		<Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority>93.5</Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority>
	</national_family>

	<national_family row ="9">
		<District_Names>Krishna </District_Names>
		<State_UT>Andhra Pradesh</State_UT>
		<Number_of_Households_surveyed>865</Number_of_Households_surveyed>
		<Number_of_Women_age_15-49_years_interviewed>820</Number_of_Women_age_15-49_years_interviewed>
		<Number_of_Men_age_15-54_years_interviewed>119</Number_of_Men_age_15-54_years_interviewed>
		<Female_population_age_6_years_and_above_who_ever_attended_school>74</Female_population_age_6_years_and_above_who_ever_attended_school>
		<Population_below_age_15_years>20.4</Population_below_age_15_years>
		<Sex_ratio_of_the_total_population_females_per_1000_males>1064</Sex_ratio_of_the_total_population_females_per_1000_males>
		<Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males>1139</Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males>
		<Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority>96.4</Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority>
	</national_family>

	<national_family row ="10">
		<District_Names>Guntur </District_Names>
		<State_UT>Andhra Pradesh</State_UT>
		<Number_of_Households_surveyed>870</Number_of_Households_surveyed>
		<Number_of_Women_age_15-49_years_interviewed>908</Number_of_Women_age_15-49_years_interviewed>
		<Number_of_Men_age_15-54_years_interviewed>139</Number_of_Men_age_15-54_years_interviewed>
		<Female_population_age_6_years_and_above_who_ever_attended_school>55.2</Female_population_age_6_years_and_above_who_ever_attended_school>
		<Population_below_age_15_years>25.9</Population_below_age_15_years>
		<Sex_ratio_of_the_total_population_females_per_1000_males>1045</Sex_ratio_of_the_total_population_females_per_1000_males>
		<Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males>918</Sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1000_males>
		<Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority>86.1</Children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority>
	</national_family>


</national_family_health_survey>




